name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: Build for ${{ matrix.goos }} and ${{ matrix.goarch }}
        run: |
          GOOS=${{ matrix.goos }}
          GOARCH=${{ matrix.goarch }}
          output_name="trek-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            output_name="${output_name}.exe"
          fi
          go build -o "$output_name" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trek-binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: trek-*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: trek-binaries-*
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/trek-*
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            See the assets below for the latest release.